-- ============================================================
-- キッチンカー出店調整アプリ / Supabase スキーマ
-- Supabase ダッシュボード > SQL Editor に貼り付けて実行してください。
-- 何度実行しても安全です（既存データは消えません）。
-- ============================================================

-- ------------------------------------------------------------
-- 1. テーブル
-- ------------------------------------------------------------

-- 出店日（イベント）
create table if not exists public.kc_events (
  id          bigint generated by default as identity primary key,
  event_date  date        not null unique,
  title       text,
  venue       text,
  target_min  smallint    not null default 2,
  target_max  smallint    not null default 3,
  note        text,
  created_at  timestamptz not null default now()
);

-- キッチンカー1台ぶんのエントリ（出店決定 / 声かけ中 / 見送り）
create table if not exists public.kc_entries (
  id          uuid        primary key default gen_random_uuid(),
  event_id    bigint      not null references public.kc_events(id) on delete cascade,
  vendor_name text        not null,
  genre       text,
  contact     text,
  status      text        not null default 'pending',
  note        text,
  position    integer     not null default 0,
  created_by  text,
  updated_by  text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint kc_entries_status_check
    check (status in ('confirmed', 'pending', 'declined'))
);

create index if not exists kc_entries_event_id_idx on public.kc_entries (event_id);
create index if not exists kc_entries_status_idx   on public.kc_entries (status);

-- ------------------------------------------------------------
-- 2. updated_at の自動更新
-- ------------------------------------------------------------
create or replace function public.kc_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists kc_entries_touch_updated_at on public.kc_entries;
create trigger kc_entries_touch_updated_at
  before update on public.kc_entries
  for each row execute function public.kc_touch_updated_at();

-- ------------------------------------------------------------
-- 3. RLS（行レベルセキュリティ）
--    publishable key（anon）だけで読み書きできるようにします。
--    ※ URL と key を知っている人は誰でも編集できます。
--       社外に共有しないでください。
-- ------------------------------------------------------------
alter table public.kc_events  enable row level security;
alter table public.kc_entries enable row level security;

drop policy if exists kc_events_public_access  on public.kc_events;
create policy kc_events_public_access
  on public.kc_events
  for all
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists kc_entries_public_access on public.kc_entries;
create policy kc_entries_public_access
  on public.kc_entries
  for all
  to anon, authenticated
  using (true)
  with check (true);

-- ------------------------------------------------------------
-- 4. Realtime（複数人での即時同期）
-- ------------------------------------------------------------
do $$
begin
  begin
    alter publication supabase_realtime add table public.kc_events;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.kc_entries;
  exception when duplicate_object then null;
  end;
end;
$$;

-- ------------------------------------------------------------
-- 5. 出店日の初期データ（10/18・10/24 は 4〜5台、その他は 2〜3台）
-- ------------------------------------------------------------
insert into public.kc_events (event_date, target_min, target_max) values
  ('2026-09-19', 2, 3),
  ('2026-09-27', 2, 3),
  ('2026-10-03', 2, 3),
  ('2026-10-18', 4, 5),
  ('2026-10-24', 4, 5),
  ('2026-11-07', 2, 3),
  ('2026-11-21', 2, 3)
on conflict (event_date) do nothing;

-- すでに登録済みの日程にも目標台数を反映する（画面から変更した値は
-- この2日程以外そのまま残ります）
update public.kc_events
   set target_min = 4, target_max = 5
 where event_date in ('2026-10-18', '2026-10-24');
